// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ff-F210bV0pTL8_bYWPg1LZCKQ4TLvI',
    appId: '1:781145982704:web:0cc5acd46cac09783de435',
    messagingSenderId: '781145982704',
    projectId: 'locaux-motion',
    authDomain: 'locaux-motion.firebaseapp.com',
    storageBucket: 'locaux-motion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR78B0uSGTb51XuE2nCprzEQxUIS-djCE',
    appId: '1:781145982704:android:0a17ea30dd213a223de435',
    messagingSenderId: '781145982704',
    projectId: 'locaux-motion',
    storageBucket: 'locaux-motion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCijnabyWfE3fw7ILr98qdomNjarbm4mh4',
    appId: '1:781145982704:ios:6e3c35dcc3e6a5633de435',
    messagingSenderId: '781145982704',
    projectId: 'locaux-motion',
    storageBucket: 'locaux-motion.appspot.com',
    iosClientId: '781145982704-43t23ok34anllsgkm1onpca3c9pkou05.apps.googleusercontent.com',
    iosBundleId: 'com.example.locauxMotion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCijnabyWfE3fw7ILr98qdomNjarbm4mh4',
    appId: '1:781145982704:ios:6e3c35dcc3e6a5633de435',
    messagingSenderId: '781145982704',
    projectId: 'locaux-motion',
    storageBucket: 'locaux-motion.appspot.com',
    iosClientId: '781145982704-43t23ok34anllsgkm1onpca3c9pkou05.apps.googleusercontent.com',
    iosBundleId: 'com.example.locauxMotion',
  );
}
